### ISSUE TITLE
Uart big len data locks dashboard

### ISSUE THREAD

**Issue by pinkflozd** [m365fw/vesc_m365_dash#2]
I tried to debug why the dash is locking up. Seems that the dash receives or sends a lot of data at once. when accelerating fast and with higher switching frequency. 

`(if (and (> len 0) (< len 10))`
seems to fix it, i think it's because of the cpu spikes the dash receives a lot of data at once

(print len) output:
```
7
7
7
7
9
7
7
7
7
85
7
7
7
7
7
7
7
7
7
```

How to reproduce the dash bug:
Set switching frequency to 45khz, connect with USB, enable live data, add a (print len), and try to hit the throttle fast, it happens on almost all fast throttles **DON'T DO IT ON ROAD!**

**Comment by 1zun4** [comment]
Yes. I have talked about this issue already with @vedderb on https://github.com/vedderb/bldc/issues/572 but have not fixed it yet. Now I can look into it. :)

**Comment by 1zun4** [comment]
The array buf is only size 64 and as soon a len of 85 is being read it will crash.

**Comment by 1zun4** [comment]
Still need to test if this actually fixes the issue.

**Comment by 1zun4** [comment]
Tested now. It does fix the issue, but it was not accurate enough. I checked if len is equal less than 60, but it has to be less than 60. 

![image](https://user-images.githubusercontent.com/69533520/213068693-62447d87-5aef-4278-8210-d8fd75f352ea.png)
works fine.

![image](https://user-images.githubusercontent.com/69533520/213068815-b637ab19-75a8-4269-869e-1fb864e722ed.png)
does.
