### ISSUE TITLE
Display does not work correctly

### ISSUE THREAD

**Issue by MatessakCZE** [m365fw/vesc_m365_dash#5]
Hey, I have just received my first vesc (75100) and I was trying to connect it to the xiaomi BLE but when I did all the things the guide said the display beeped dots went down until only one was left and it started blinking. When I tried the throttle it worked but after connect the ble, controlling the motor through throttle or via vesc tool makes the motor do weird things vibrate and rotate only a little. Without the BLE everything works as expected.

**Comment by MatessakCZE** [comment]
I am using flipsky and also how do I flash the firmware if I do not have the original esc? Is it even possible? Thanks!

**Comment by Nikolai521** [comment]
Nah just in case if you have the model with the design flaw

the typical behavior is just jerking, impossible to start from 0, hall issues, noise
this apply just for the 75100 v2 box model

**Comment by MatessakCZE** [comment]
I just received the new display, but I still have one problem, whatever I do the button seems to not be working. If I enable poll mode in vesc tool to see if it is recognizing the presses, when I press the button the poll status freezes and it comes back after a while. The only way I can make the throttle and brake work again is holding brake and pressing throttle twice.

**Comment by MatessakCZE** [comment]
nvm I was connecting it wrong, Thanks for the help!
