### ISSUE TITLE
The light is always on a little bit

### ISSUE THREAD

**Issue by MatessakCZE** [m365fw/vesc_m365_dash#8]
Also, I have a problem where even if the display is turned off the light is always a little bit lit it is dim but I am wondering if it is draining my battery. 
Thanks!

**Comment by Nikolai521** [comment]
The front light works with at about 6.4v (in my case), the display uses a small step up regulator for provide the voltage to the led when its on, when its off, it just bypasses the 5v directly to the led

Also the voltage from VESC is a bit more high than stock ninebot controller, i fixed this adding a normal diode (i recommend a 2 or 3amp one) on the 5v line, it drops the voltage about 0.6v (you get about 4.6v to display) but this makes the led fully shuts off
