### ISSUE TITLE
G30 throttle and brake recognized but not functioning.

### ISSUE THREAD

**Issue by MatessakCZE** [m365fw/vesc_m365_dash#9]
Hi, I have a m365 with flipsky 75100 vesc. I wanted to get the extra features from a lisp that is only compatible with g30 and not m365 that is based of of this one. Problem is, the throttle and brake is recognized but it isn't doing anything to the motor. Neither when I spin the motor through vesc app and try to brake, or when i try to run the motor using the throttle.
I ofc already tried using the original code from here but it isn't working either.

What could it be? Is the wiring different in theese two BLE's? Or is it something else?

**Comment by Nikolai521** [comment]
You have the code for both displays, i tired on G30 and pro1 and pro2 display and worked nice
The thorttle input needs to be enabled and configured in vesc (app > general > adc enabled > adc >current based or whatever you want)

Also look if you really are using vesc 6.05 firmware, now we have 6.06 on beta and still working perfectly

**Comment by Nikolai521** [comment]
> m365 ble it just worked without any additional settings
Sounds like you are using the old script? both ones works in the same way, comunicates directly with the adc values so you need to turn on live app on vesc and you can see the thorttle + brake values live

**Comment by MatessakCZE** [comment]
I haven't tried the m365 code after the firmware update to 6.5, so settings got cleared out.

**Comment by 1zun4** [comment]
> Ohh, I did not know I had to have adc enabled. With m365 ble it just worked without any additional settings. And yes, I am sure I'm using 6.5. Thank you so much, will try it tomorrow!

This has changed since 6.05. ADC offers much better customisation and is more compatible with VESC. The solution before 6.05 was a bit shaky and did not support dual motors out of the box, or even traction control and so on.

I hope you figured it out. Since you did not write back, I will consider this issue as resolved and close it. If not, reply and I will respond as soon as possible.
